project:
  type: website

website:
  title: "Walker Lab at GW"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: courses.qmd
        text: Courses

format:
  html:
    theme:
      - lumen
      - brand
    css: styles.css
    toc: true



